SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) B
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES
ORDER BY A.FOOD_TYPE DESC;

SELECT I1.FOOD_TYPE, I1.REST_ID, I1.REST_NAME, I1.FAVORITES FROM REST_INFO AS I1
WHERE (I1.FOOD_TYPE, I1.FAVORITES) IN (SELECT I2.FOOD_TYPE, MAX(I2.FAVORITES) FROM REST_INFO AS I2 GROUP BY I2.FOOD_TYPE)
ORDER BY I1.FOOD_TYPE DESC